port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: false
hosts:
  mtalk.google.com: 108.177.125.188
  raw.githubusercontent.com: 151.101.76.133
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  use-hosts: true
  nameserver-policy: { '*.google.com': 8.8.8.8, '*.tw': 1.1.1.1, testflight.apple.com: 8.8.8.8, '*.tmall.com': 223.5.5.5, '*.taobao.com': 223.5.5.5, '*.alicdn.com': 223.5.5.5, '*.aliyun.com': 223.5.5.5, '*.alipay*.com': 223.5.5.5, '*.alibaba*.com': 223.5.5.5, '*.alimama*.com': 223.5.5.5, '*.qq.com': 114.114.114.114, '*.tencent.com': 114.114.114.114, '*.weixin.com': 114.114.114.114, '*.qpic.cn': 114.114.114.114, '*.jd.com': 114.114.114.114, '*.bilibili.com': 114.114.114.114, hdslb.com: 114.114.114.114, '*.163.com': 119.29.29.29, '*.126.com': 119.29.29.29, '*.126.net': 114.114.114.114, '*.127.net': 114.114.114.114, '*.netease.com': 114.114.114.114, '*.10010.com': 114.114.114.114, '*.unicompayment.com': 114.114.114.114, '*.ximalaya.com': 114.114.114.114, '*.baidu.com': 114.114.114.114, '*.bdstatic.com': 114.114.114.114 }
  default-nameserver: ['https://hk.pro.xns.one/PSzRUiRrv0o/dns-query']
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - stun.*.*
    - stun.*.*.*
    - swscan.apple.com
    - mesu.apple.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - xbox.*.*.microsoft.com
    - '*.*.xboxlive.com'
    - '*.ipv6.microsoft.com'
    - teredo.*.*.*
    - teredo.*.*
    - speedtest.cros.wr.pvp.net
    - +.jjvip8.com
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
external-controller: 127.0.0.1:9090
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
